name: Tests

on:
  push:
    branches:
    - main
    - develop

  pull_request:
    branches:
    - main
    - develop

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Retrieve the cached "node_modules" directory (if present)
      uses: actions/cache@v2
      id: node-cache
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies (if the cached directory was not found)
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Run Tests
      run: |
        npm run -- test --color
